apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJMU1USXhOVEExTkRBek5Wb1hEVE0xTVRJeE16QTFOREF6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS0lOCnFwYVN5eCtMSFk4WVNFTzJwKzZyY0hnTWQ5Q0ZMY2g2ZHNWU2tpUCtBYkVtK1BJdm93cm8rdDBZdUJLVUlNWE0KVXp5YkRqZ2tMZTRTWThwdDVNS1czS0kvV1FPSHdoSlVyU1ppa29ybFJwS0kzcitUZ0dEQ2Uyb1kzMnVJeFNzRgpHblJzN2N3ODRmNXcyMGtpeVpXRTFOQ2RnckQvUVVNSndlWnY4dkMwNW1VbURYeDgvdjVjY20ya004UHNHcE9RCkdxNCsrdlFUTmtjbDByWC9mN0hzUkY3RVNBdjh4cU12NkpuQ2RvSG1WMFlGZ2pHc0lTdEIrS0VyS2UvUzBRWXAKNTdqelB3RmpGdGppNlJVeHllRzdEYkRXS1c0SkVLTXczR3lnNUNYRzFZbmVkUzdaQlBmcERyOUVUeldUSE9OSgpqQ24zemdicVZUNVh0dFAvUTBrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZNbkNlV3lMV0JwU1dzYzNtYm9xRS95ZzBRcy9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBaXFwRWdPNWxzQ2NONlQzTDJsZEJGNG8wM3FwcEZZUHp2YTcrTml2anBEYUppbDRncwplNkpsbGZ0Y3ZBNkFxbGVubldURmJvZG16ZitsczNvbmZ1QlRZRDBWUTUrRE9CR2JGWHkzZU9lNmZaY0xYZi9FClY0d1VCSkxGeUMzWFVwWVUyNDYvelc2d0I0U1FONmhYK1E3SjlvdTNEcUJVZlA2cTl3MjJ4eWIwbG4yUW1RYWoKZmtQYWxLNTBNOWNpN0dZTmdRVlRFVjB6cUxCN09qMnViSG9Ocy9jdXBzdmkveE8wQmxHT296NTJpWmRoRWhCcQo5c253UFZlQ3IrQnJWUVBrK05HN0tFZmw4Nk5DVmF0ZmJ0WWxsbXpBNmgxQWtzV200cTJJdEhvRThISkx6Zis5Ckw2TWl5UGxRMzN5eFRURG9CTnhPaUpjc2c5V2JmdHRoNVNwbQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://178.154.206.100
  name: yc-managed-k8s-catantfp5v55kp20ndpd
contexts:
- context:
    cluster: yc-managed-k8s-catantfp5v55kp20ndpd
    user: yc-managed-k8s-catantfp5v55kp20ndpd
  name: yc-credit-scoring-cluster
current-context: yc-credit-scoring-cluster
kind: Config
preferences: {}
users:
- name: yc-managed-k8s-catantfp5v55kp20ndpd
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - k8s
      - create-token
      - --profile=default
      command: /opt/homebrew/bin/yc
      env: null
      provideClusterInfo: false
